# Generated by Django 4.1.5 on 2023-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('profile_picture', models.ImageField(blank=True, upload_to='people/profile-pictures', verbose_name='Profile Picture')),
                ('art_work', models.FileField(blank=True, upload_to='people/art-works', verbose_name='Art Work')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Email')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('qualification', models.CharField(blank=True, max_length=250, verbose_name='Qualification')),
                ('is_current_employee', models.BooleanField(default=True, verbose_name='Is Current Employee')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, max_length=500, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
            },
        ),
    ]
