# Generated by Django 4.1.5 on 2023-01-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='art_work',
            field=models.FileField(blank=True, upload_to='people/art-works', verbose_name='Art Work'),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='people/profile-pictures', verbose_name='Profile Picture'),
        ),
    ]
