# Generated by Django 4.1.5 on 2023-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_art_work_alter_people_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
