# Generated by Django 4.1.5 on 2023-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_founder',
            field=models.BooleanField(default=False, verbose_name='Is Founding Member'),
        ),
    ]
