# Generated by Django 4.2.23 on 2026-04-15 06:27

from django.db import migrations
import gaatha.utils


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_people_is_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='art_work',
            field=gaatha.utils.SecureFileField(blank=True, upload_to='people/art-works', verbose_name='Art Work'),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_picture',
            field=gaatha.utils.SecureImageField(blank=True, upload_to='people/profile-pictures', verbose_name='Profile Picture'),
        ),
    ]
