services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    restart: unless-stopped
    image: gaatha-server/server
    build:
      context: ./
    tty: true
    environment:
      DEBUG: ${DEBUG:-True}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
      # Domain configs
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?err}
      APP_DOMAIN: ${APP_DOMAIN:-http://localhost:8020}
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN:-http://localhost:3000}  # NOTE: Not used right now
      SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN:-localhost}
      CSRF_COOKIE_DOMAIN: ${CSRF_COOKIE_DOMAIN:-localhost}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PWD: ${DB_PWD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      LANGUAGE_CODE: ${LANGUAGE_CODE:-en-us}
      TIME_ZONE: ${TIME_ZONE:-Asia/Kathmandu}
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./:/code
    ports:
      - '8020:8020'
    depends_on:
      - db

volumes:
  postgres-data:
