services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    image: $DOCKER_IMAGE_BACKEND
    stdin_open: true
    tty: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: ./
    environment:
      CI: "true"
      DEBUG: "true"
      DJANGO_SECRET_KEY: "XXXXXXXXXXXXXXXXXXXX"
      APP_DOMAIN: http://localhost:8020
      FRONTEND_DOMAIN: http://localhost:3000
      SESSION_COOKIE_DOMAIN: localhost
      CSRF_COOKIE_DOMAIN: localhost
      APP_ENVIRONMENT: CI
      ALLOWED_HOSTS: '*'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: db
      DB_PORT: 5432
      LANGUAGE_CODE: en-us
      TIME_ZONE: Asia/Kathmandu
    volumes:
      - ./ci-share/:/ci-share/
    depends_on:
      - db

volumes:
  postgres-data:
