# Generated by Django 4.1.5 on 2023-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Visualization', 'verbose_name_plural': 'Visualizations'},
        ),
    ]
