app:
  environment: Alpha
  image:
    name: ghcr.io/stories-of-gaatha/gaatha-server-dev
    tag: latest

  ingress:
    enabled: true
    className: nginx
    host: test.com

  redis:
    master:
      persistence:
        size: .5Gi
        storageClass: longhorn

  postgresql:
    enabled: true
    auth:
      postgresPassword: "testing-password"
      username: "test"
      password: "testing-password"
      database: "test"
    primary:
      persistence:
        storageClass: "longhorn"
        size: 1Gi

  minio:
    enabled: true
    global:
      defaultStorageClass: longhorn
    apiIngress:
      enabled: true
      ingressClassName: nginx
      hostname: gaatha-minio-test.com
    auth:
      rootUser: gaatha
      rootPassword: "test"
    persistence:
      enabled: true
      size: 0.5Gi
  # NOTE: Check main/settings.py for all available options
  env:
    # App Domain
    SESSION_COOKIE_DOMAIN: .test.com
    CSRF_COOKIE_DOMAIN: .test.com
    APP_TYPE: "WEB"
    APP_DOMAIN: "https://gaatha.com"
    DJANGO_DEBUG: "false"
    TIME_ZONE: "Asia/Kathmandu"
    FRONTEND_DOMAIN: "https://gaatha-frontend.com"
    SESSION_COOKIE_DOMAIN: "https://test-session.com"
    CSRF_COOKIE_DOMAIN: "https://test-cookie.com"
    # AWS
    AWS_S3_ENDPOINT_URL: "https://gaatha.minio.com"
    AWS_S3_STATIC_BUCKET_NAME: "static-data"
    AWS_S3_MEDIA_BUCKET_NAME: "media-data"

  secrets:
    DJANGO_SECRET_KEY: "very-secret-key"
    # Postgres
    DB_NAME: "test"
    DB_USER: "test"
    DB_PWD: "test"
    DB_HOST: "test"
    DB_PORT: "test"
  #AWS
  AWS_S3_ACCESS_KEY_ID: "test"
  AWS_S3_SECRET_ACCESS_KEY: "test"
  AWS_S3_REGION_NAME: "us-east-1"
