name: Gaatha server GH Actions

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    name: Build + Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Validate latest graphql schema.
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker-compose -f ./gh-docker-compose.yml run --rm server bash -c 'wait-for-it db:5432 && ./manage.py generate_schema --out /ci-share/schema-latest.graphql' &&
          cmp --silent schema.graphql ./ci-share/schema-latest.graphql || {
            echo 'The schema.graphql is not up to date with the latest changes. Please update and push latest';
            diff schema.graphql ./ci-share/schema-latest.graphql;
            exit 1;
          }

      - name: Validate if there are no pending django migrations.
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker-compose -f ./gh-docker-compose.yml run --rm server bash -c 'wait-for-it db:5432 && ./manage.py makemigrations --check --dry-run' || {
            echo 'There are some changes to be reflected in the migration. Make sure to run makemigrations';
            exit 1;
          }

      - name: Run Test
        env:
          DOCKER_IMAGE_SERVER: ${{ steps.prep.outputs.tagged_image }}
        run: |
          docker-compose -f gh-docker-compose.yml run --rm server /code/scripts/run_tests.sh

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'develop:schema.graphql'
          fail-on-breaking: false
