# Generated by Django 4.2.23 on 2025-11-30 14:58

from django.db import migrations, models
import django.db.models.deletion
import gaatha.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=225)),
                ('work_type', models.CharField(choices=[('architecture', 'Architecture'), ('graphics_and_visualizations', 'Graphics and Visualizations')], default='architecture', max_length=225)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('art_work', gaatha.utils.SecureFileField(blank=True, null=True, upload_to='work/art-works')),
                ('is_cover_image_dark', models.BooleanField(default=False, verbose_name='Is Cover Image Dark ?')),
                ('cover_image', gaatha.utils.SecureImageField(blank=True, null=True, upload_to='work/cover-images', verbose_name='Cover image')),
                ('area', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=250, verbose_name='Status')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', gaatha.utils.SecureImageField(upload_to='work-image/images/', verbose_name='Image')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workimage_work', to='work.work', verbose_name='Work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_category', to='work.workcategory', verbose_name='Category'),
        ),
    ]
