# Generated by Django 4.1.5 on 2023-01-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('art_work', models.FileField(blank=True, null=True, upload_to='art_works')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images', verbose_name='Cover image')),
                ('area', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('category_1', 'Category 1'), ('category_2', 'Category 2')], max_length=50, verbose_name='Category')),
                ('status', models.CharField(max_length=250, verbose_name='Status')),
                ('tag', models.CharField(choices=[('tag_1', 'Tag 1'), ('tag_2', 'Tag 2')], max_length=50, verbose_name='Tag')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workimage_image', verbose_name='Image')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workimage_work', to='work.work', verbose_name='Work')),
            ],
        ),
    ]
