# Generated by Django 4.1.5 on 2023-01-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Profile Picture')),
                ('art_work', models.FileField(blank=True, null=True, upload_to='art_works', verbose_name='Art Work')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('qualification', models.CharField(blank=True, max_length=250, verbose_name='Qualification')),
                ('is_current_employee', models.BooleanField(default=True)),
                ('linked_in_url', models.CharField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('instagram_url', models.CharField(blank=True, max_length=500, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('art_work', models.FileField(blank=True, null=True, upload_to='art_works')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images', verbose_name='Cover image')),
                ('area', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('residental', 'Residental'), ('civic', 'Civic'), ('landscape', 'Landscape'), ('research', 'Research')], max_length=50, verbose_name='Category')),
                ('status', models.CharField(max_length=250, verbose_name='Status')),
                ('tag', models.CharField(choices=[('architecture', 'Architecture'), ('interior', 'Interior'), ('graphics', 'Graphics'), ('visualization', 'Visualization'), ('exibition', 'Exibition')], max_length=50, verbose_name='Tag')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workimage_image', verbose_name='Image')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workimage_work', to='work.work', verbose_name='Work')),
            ],
        ),
    ]
