# Generated by Django 4.1.5 on 2023-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_cover_image_dark',
            field=models.BooleanField(default=False, verbose_name='Is Cover Image Dark ?'),
        ),
    ]
