# Generated by Django 4.1.5 on 2023-03-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_is_cover_image_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
