# Generated by Django 4.1.5 on 2023-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='sub_title',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
