# Generated by Django 4.1.5 on 2023-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='tag',
        ),
        migrations.DeleteModel(
            name='WorkTag',
        ),
    ]
