# Generated by Django 4.1.5 on 2023-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_work_tag_delete_worktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('architecture', 'Architecture'), ('graphics_and_visualizations', 'Graphics and Visualizations')], default='architecture', max_length=225),
        ),
    ]
