# Generated by Django 4.2.23 on 2026-04-15 06:27

from django.db import migrations
import gaatha.utils


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_work_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='art_work',
            field=gaatha.utils.SecureFileField(blank=True, null=True, upload_to='work/art-works'),
        ),
        migrations.AlterField(
            model_name='work',
            name='cover_image',
            field=gaatha.utils.SecureImageField(blank=True, null=True, upload_to='work/cover-images', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=gaatha.utils.SecureImageField(upload_to='work-image/images/', verbose_name='Image'),
        ),
    ]
